version: '3.8'
services:
  db:
    container_name: roadAssistantDevDb
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: roadAssistantDevDb
    ports:
      - "5432:5432"
    volumes:
      - roadAssistantDevDb:/var/lib/postgresql/data
  prometheus:
    container_name: devPrometheus
    image: prom/prometheus:v2.44.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "7070:9090"

volumes:
  roadAssistantDevDb:
    driver: local