scrape_configs:
  - job_name: 'Metrics for RoadAssistant'
    metrics_path: /actuator/prometheus
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          application: RoadAssistant